const BOOKING_STATUS = require("../constants/bookingStatus");

const bookingTransitions = {
  [BOOKING_STATUS.ACTION_PENDING]: {
    ADMIN1: [
      BOOKING_STATUS.ADMIN1_APPROVED,
      BOOKING_STATUS.CHANGE_REQUESTED,
      BOOKING_STATUS.REJECTED
    ]
  },

  [BOOKING_STATUS.ADMIN1_APPROVED]: {
    ADMIN2: [
      BOOKING_STATUS.PAYMENT_REQUESTED,
      BOOKING_STATUS.REJECTED
    ]
  },

  [BOOKING_STATUS.PAYMENT_REQUESTED]: {
    USER: [BOOKING_STATUS.PAYMENT_COMPLETED]
  },

  [BOOKING_STATUS.PAYMENT_COMPLETED]: {
    ADMIN2: [BOOKING_STATUS.ADMIN2_APPROVED]
  },

  [BOOKING_STATUS.ADMIN2_APPROVED]: {
    ADMIN3: [
      BOOKING_STATUS.ADMIN3_APPROVED,
      BOOKING_STATUS.REJECTED
    ]
  }
};

module.exports = bookingTransitions;
