const BOOKING_STATUS = {
  ACTION_PENDING: "ACTION_PENDING",
  CHANGE_REQUESTED: "CHANGE_REQUESTED",
  REJECTED: "REJECTED",

  ADMIN1_APPROVED: "ADMIN1_APPROVED",

  PAYMENT_REQUESTED: "PAYMENT_REQUESTED",
  PAYMENT_COMPLETED: "PAYMENT_COMPLETED",

  ADMIN2_APPROVED: "ADMIN2_APPROVED",
  ADMIN3_APPROVED: "ADMIN3_APPROVED"
};

module.exports = BOOKING_STATUS;
